# Generated by Django 4.1.7 on 2023-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
