# Generated by Django 4.1.7 on 2023-03-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer"},
        ),
    ]
