# Generated by Django 4.1.7 on 2023-03-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_customer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "managed": True,
                "verbose_name": "Customer",
                "verbose_name_plural": "Customer",
            },
        ),
    ]
