# Generated by Django 4.1.7 on 2023-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="cart",
            name="amount",
            field=models.CharField(max_length=10),
        ),
    ]
