# Generated by Django 4.1.7 on 2023-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_cart_quantity_alter_cart_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart",
            name="paid",
            field=models.BooleanField(default=True),
        ),
    ]
