# Generated by Django 4.1.7 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="address",
            field=models.TextField(default="a"),
        ),
    ]
